Update newPMD.yml

diff --git a/.github/workflows/newPMD.yml b/.github/workflows/newPMD.yml
--- a/.github/workflows/newPMD.yml
+++ b/.github/workflows/newPMD.yml
@@ -1,31 +1,56 @@
-name: newPMD
-
-on: [push]
+name: PMD Static Code Analysis
+on:
+  pull_request:
+    branches:
+      - main
+  push:
+    branches:
+      - main
+  workflow_dispatch:
 
 jobs:
-  pmd:
-  
+  pmd-analyser-check:
+    name: PMD Static Code Analysis
+    permissions:
+      security-events: write
+      actions: read
+      contents: read
     runs-on: ubuntu-latest
-    
     steps:
-      - name: PMD Analyser
-    # You may pin to the exact commit or the version.
-    # uses: synergy-au/pmd-analyser-action@e2087952f602f940871d32ba51445e28d08b057c
+      - name: Checkout Repository
+        uses: actions/checkout@v2
+        with:
+          # Incremental diffs require fetch depth to be at 0 to grab the target branch
+          fetch-depth: '0'
+      - name: Run Full PMD Analysis
+        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
+        id: pmd-full-analysis
         uses: synergy-au/pmd-analyser-action@v2.1
         with:
-          # Used to determine whether you just want to analyse the files changed or the whole repository.
-          analyse-all-code: false
-          # If you are looking to compare the file difference based on the GitHub pull request, you will need to specify the [GitHub secrets token](https://docs.github.com/en/actions/reference/authentication-in-a-workflow)
-          # auth-token: # optional
-          # If you wish to define rules that log as an error, enter each rule name separated with a comma and no spaces. Note that if an error is identified the run will fail. e.g. ClassNamingConventions,GuardLogStatement
-          # error-rules: # optional
-          # Choose whether you want the file comparison to be based on a git diff or based on the files changed specified on the GitHub pull request. Note that if you use the GitHub pull request option, this action will only work on a pull request event. Options to set this are either `git` or `github`.
-          # file-diff-type: # optional, default is git
-          # Path to the sources to analyse. This can be a file name, a directory, or a jar or zip file containing the sources.
-          file-path: ./classes/
-          # If you wish to define rules that log as a note, enter each rule name separated with a comma and no spaces. Note that if a note is identified the run will not fail. e.g. ClassNamingConventions,GuardLogStatement
-          # note-rules: # optional
-          # The version of PMD you would like to run. You can either specify latest to always get the newest version, or you can specify a version number like 6.37.0
-          # pmd-version: # optional, default is latest
-          # The ruleset file you want to use. PMD uses xml configuration files, called rulesets, which specify which rules to execute on your sources. You can also run a single rule by referencing it using its category and name (more details here). For example, you can check for unnecessary modifiers on Java sources with -R category/java/codestyle.xml/UnnecessaryModifier.
-          rules-path: ./rulesets/apexruleset.xml
+          analyse-all-code: 'true'
+          pmd-version: 'latest'
+          file-path: './src'
+          rules-path: './pmd-ruleset.xml'
+          error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
+          note-rules: 'ApexDoc'
+      - name: Run PMD Analysis on Files Changed
+        id: pmd-partial-analysis
+        if: github.event.pull_request != null
+        uses: synergy-au/pmd-analyser-action@v2.1
+        with:
+          pmd-version: 'latest'
+          file-path: './src'
+          rules-path: './rulesets/apexruleset.xml'
+          error-rules: 'AvoidDirectAccessTriggerMap,AvoidDmlStatementsInLoops,AvoidHardcodingId'
+          note-rules: 'ApexDoc'
+      #- name: Upload results to GitHub
+       # uses: github/codeql-action/upload-sarif@v1
+        #with:
+         # sarif_file: pmd-output.sarif
+      - name: Any PMD Errors?
+        run: |
+          if ${{ steps.pmd-full-analysis.outputs.error-found }} ${{ steps.pmd-partial-analysis.outputs.error-found }}
+          then
+            echo "PMD failed with errors"
+            exit 3
+          fi
